SELECT DISTINCT
    MEM.MEM_NUM             AS "MEMBER_NUMBER",
    TXN.ROW_ID 				AS "TXN_ID",
    PROD.NAME 				AS "PRODUCT_NAME",
    TXNX.ROW_ID 			AS "TXNX_ROW_ID",
    TXNX.X_SIGN_MEMBER_ID	AS "X_SIGN_MEMBER_ID",
    TXN.PAR_TXN_ID			AS "PAR_TXN_ID",
    TXNSIGN.ROW_ID 			AS "SIGN_CLUB_ID__IN__PAR_TXN_ID",
    SGPARAM.PLAN_TYPE		AS "PLAN_TYPE",
    CASE
        WHEN MEMSIGN.ROW_ID IS NOT NULL THEN 'Y'
        ELSE 'N'
    END 					AS "ASSINATURA_CORRETA_FLG",
    CASE
		WHEN SGPARAM.PLAN_TYPE = 'Annual - In Cash' OR SGPARAM.PLAN_TYPE = 'Annual - Parcelled' THEN
			FIRST_VALUE(PAGTXN.PGT_TXN_ID) OVER (PARTITION BY TXN.ROW_ID ORDER BY PAG.CREATED) 					-- Se o plano for anual, busca a primeira transa��o de ac�mulo do primeiro pagamento
		ELSE
			FIRST_VALUE(PAG.X_ATTRIB_07) OVER (PARTITION BY TXN.ROW_ID ORDER BY PAG.CREATED) 					-- Se o plano for mensa, busca a transa��o indicada no primeiro pagamento
    END 					AS "TXN_ADESAO"
FROM SIEBEL.S_LOY_TXN TXN
INNER JOIN SIEBEL.S_PROD_INT PROD ON PROD.ROW_ID = TXN.PROD_ID
INNER JOIN SIEBEL.S_LOY_MEMBER MEM ON MEM.ROW_ID = TXN.MEMBER_ID
INNER JOIN SIEBEL.CX_SIGN_MEMBER TXNSIGN ON TXNSIGN.X_ATTRIB_12 = TXN.PAR_TXN_ID 								-- > Assinatura gravada no par_txn_id
INNER JOIN SIEBEL.CX_PARAM_CLUBE SGPARAM ON SGPARAM.ROW_ID = TXNSIGN.X_ATTRIB_04
LEFT JOIN SIEBEL.CX_SIGN_MEMBER MEMSIGN ON MEMSIGN.X_ATTRIB_01 = MEM.ROW_ID AND MEMSIGN.ROW_ID = TXNSIGN.ROW_ID	-- > Para garantir que a assinatura gravada no par_txn_id � do cliente
LEFT JOIN SIEBEL.S_LOY_TXN_X TXNX ON TXNX.PAR_ROW_ID = TXN.ROW_ID
LEFT JOIN SIEBEL.CX_PAG_CLUB PAG ON PAG.X_ATTRIB_01 = TXNSIGN.ROW_ID
LEFT JOIN (
	SELECT DISTINCT
		PAGCLUBTXN.PAR_ROW_ID,
		FIRST_VALUE(TXNPAG.ROW_ID) OVER (PARTITION BY PAGCLUBTXN.PAR_ROW_ID ORDER BY TXNPAG.TXN_DT) AS PGT_TXN_ID
	FROM SIEBEL.CX_PAG_CLUB_TXN PAGCLUBTXN
	INNER JOIN SIEBEL.S_LOY_TXN TXNPAG ON TXNPAG.ROW_ID = PAGCLUBTXN.TXN_ID
	WHERE 1=1
	AND TXNPAG.TYPE_CD = 'ACCRUAL'
) PAGTXN ON PAGTXN.PAR_ROW_ID = PAG.ROW_ID 																		-- > Busca pela primeira transa��o de accrual dos pagamentos. Quando clube anual
WHERE 1=1
AND PROD.NAME LIKE 'XXXXXXXXX%Ades�o%'
ORDER BY MEM.MEM_NUM, TXN.ROW_ID;