select * from dba_directories;

--> PROGRAM ORGANIZATION
SELECT
    PRG.ROW_ID  AS "PROG_ID",
    PRG.NAME    AS "PRG_NAME",
    BU.ROW_ID   AS "BU_ID",
    BU.NAME     AS "ORG_NAME"
FROM SIEBEL.S_LOY_PROGRAM PRG
INNER JOIN SIEBEL.S_BU BU ON BU.ROW_ID = PRG.BU_ID
WHERE 1=1
AND PRG.NAME = 'Programa XXXXXX'; -- PROGRAM NAME

--> PARTNER ORGANIZATION
SELECT
    PAR.BU_ID,
	PAR.NAME			AS "PARTNER_NAME",
    PAR.ALIAS_NAME      AS "ALIAS"
FROM SIEBEL.S_LOY_PROGRAM PROG
INNER JOIN SIEBEL.S_LOY_PROG_ORG PORG ON PORG.PROG_ID = PROG.ROW_ID
INNER JOIN SIEBEL.S_ORG_EXT PAR ON PAR.ROW_ID = PORG.ORG_EXT_ID
WHERE 1=1
AND PROG.ROW_ID = '1-1W24X' -- PROGRAM ID
AND PAR.BU_ID = '1-1WSYY'	-- ORGANIZATION ID
AND PAR.ALIAS_NAME = 'AAA';	-- PARTNER ALIAS

--> MEMBER ORGANIZATION
SELECT
    MBR.ROW_ID      AS "MBR_ID",
    MBR.MEM_NUM     AS "MBR_NUM",
    MBR.BU_ID       AS "MBR_BU_ID",
    BUM.NAME        AS "MBR_BU_NAME"
FROM SIEBEL.S_LOY_MEMBER MBR
INNER JOIN SIEBEL.S_BU BUM ON BUM.ROW_ID = MBR.BU_ID
WHERE 1=1
AND MBR.MEM_NUM = '106968746'; -- MEMBER NUMBER

--> PARENT TRANSACTION
SELECT
    TXN.BU_ID,
    TXN.TXN_NUM
FROM SIEBEL.S_LOY_TXN TXN
WHERE TXN.ROW_ID = '1-1NXHUTOE'; -- ROW_ID DA TXN DE RECORRENCIA

--> TRANSACTION POINTS
SELECT
    ATR.ATTR_TYPE_CD    AS "POINT_TYPE",
    ATR.INTERNAL_NAME   AS "POINT_NAME"
FROM SIEBEL.S_LOY_ATTRDEFN ATR
WHERE 1=1
AND ATR.PROGRAM_ID = '1-1W24X'	-- PROGRAM ID
AND ATR.DISPLAY_NAME = 'Milhas'	-- FIXED COLUMN
AND ATR.OBJECT_CD = 'Member';	-- FIXED COLUMN

--> TRANSACTION PRODUCT DETAILS
SELECT
    PROD.ROW_ID     AS "PROD_ID",
    PROD.NAME       AS "PROD_NAME",
    PROD.PART_NUM   AS "PROD_PART",
    PROD.BU_ID      AS "PROD_BU",
    PAR.ROW_ID      AS "PARTNER_ID",
    PAR.BU_ID       AS "PARTNER_ORG",
    PAR.LOC         AS "PARTNER_LOC",
    PAR.NAME        AS "PARTNER_NAME",
    PAR.ALIAS_NAME  AS "PARTNER_ALIAS"
FROM SIEBEL.S_PROD_INT PROD
LEFT JOIN SIEBEL.S_PGM_ORG_PROD PPRD ON PPRD.PRODUCT_ID = PROD.ROW_ID
LEFT JOIN SIEBEL.S_LOY_PROG_ORG PRGO ON PRGO.ROW_ID = PPRD.PROG_PARTNER_ID
LEFT JOIN SIEBEL.S_ORG_EXT PAR ON PAR.ROW_ID = PRGO.ORG_EXT_ID
WHERE 1=1
AND PROD.NAME = 'XXXXXXX Cartão Infinite Adesão Club XXXXXX'    -- PRODUCT NAME
AND PAR.ALIAS_NAME = 'AAA'; -- PARTNER ALIAS